language: php
php:
  - 7.1

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - bash ./deploy.sh
on:
  branch: master