language: php
php:
- 7.1
script:
- bash ./deploy.sh
true:
  branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_ae70f514faa2_key -iv $encrypted_ae70f514faa2_iv
  -in deploy_key.enc -out ./deploy_key -d
  
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key -p 2222 jrpiresc@108.167.188.84 pwd